version: "3.7"
services:
  backend:
    environment:
      - NODE_ENV
      - PROTOCOL
      - DOMAIN
      - PROJECT_NAME
      - FIRST_SUPERUSER
      - FIRST_SUPERUSER_PASSWORD
      - EMAILS_FROM
      - OPEN_USER_REGISTRATION
      - TYPEORM_CONNECTION
      - TYPEORM_HOST
      - TYPEORM_USERNAME
      - TYPEORM_PASSWORD
      - TYPEORM_DATABASE
      - TYPEORM_PORT
      - TYPEORM_SYNCHRONIZE
      - TYPEORM_ENTITIES
      - TYPEORM_MIGRATIONS_TABLE_NAME
      - TYPEORM_MIGRATIONS_DIR
      - TYPEORM_MIGRATIONS
      - JWT_SECRET
      - REDIS_HOST
      - REDIS_PORT
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - app_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`, `/ws`, `/docs`, `/redoc`)"
      - "traefik.http.routers.backend.entrypoints=web"
    networks:
      default:
        aliases:
          - DOMAIN

  worker:
    environment:
      - NODE_ENV
      - SMTP_TLS
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
    depends_on:
      - rabbitmq
    volumes:
      - worker_data:/data
    labels:
      - "traefik.enable=true"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  db:
    restart: always
    image: postgres:15.10-alpine
    environment:
      - POSTGRES_SERVER=${TYPEORM_HOST}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    restart: always
    image: dpage/pgadmin4:8.14
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5050:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    restart: always
    image: rabbitmq:3.8.16-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    restart: always
    image: redis:6.2.3-alpine3.13
    environment:
      - REDIS_HOST
      - REDIS_PORT
    volumes:
      - redis_data:/data

  redisinsight:
    restart: always
    image: redislabs/redisinsight:1.10.1
    depends_on:
      - redis
    ports:
      - 8001:8001
    volumes:
      - redisinsight_data:/db

  portainer:
    restart: always
    image: portainer/portainer-ce:2.1.1-alpine
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000

  proxy:
    restart: always
    image: traefik:2.4.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080

volumes:
  app_data:
  worker_data:
  postgres_data:
  portainer_data:
  redis_data:
  redisinsight_data:
  rabbitmq_data:
  pgadmin_data:
